/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import QuanLyBanHang.BUS.phanquyenBUS;
import QuanLyBanHang.DTO.phanquyen;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;
import jpanel.jpanelBanHang;
import jpanel.jpanelKhachHang;
import jpanel.jpanelKhuyenMai;
import jpanel.jpanelNhanVien;
import jpanel.jpanelNhapHang;
import jpanel.jpanelSanPham;
import jpanel.jpanelThongKe;

/**
 *
 * @author giangdeptrai
 */
public class GiaoDienAdmin1 extends javax.swing.JFrame {

    private JPanel banHang;
    private JPanel khuyenMai;
    private JPanel sanPham;
    private JPanel nhanVien;
    private JPanel khachHang;
    private JPanel thongKe;
    private JPanel nhapHang;
    jpanelBanHang jpnbanhang;
    jpanelKhachHang jpnkhachang;
    jpanelKhuyenMai jpnkhuyenmai;
    jpanelNhapHang jpnnhaphang;
    jpanelNhanVien jpnnhanvien;
    jpanelSanPham jpnsanpham;
    jpanelThongKe jpnthongke;
    /**
     * Creates new form GiaoDienAdmin1
     */
    public GiaoDienAdmin1() {
        initComponents();
//        this.setTitle("Phần mềm quản lý cửa hàng thời trang");
//        this.setBackground(Color.yellow);
//        this.setFont(new Font("Time new roman", Font.PLAIN, 16));
        Image icon = Toolkit.getDefaultToolkit().getImage("src/img/mau-logo-shop-quan-ao-7.jpg");
        this.setIconImage(icon);
        addControls();
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnBanHang = new javax.swing.JPanel();
        lblBH = new javax.swing.JLabel();
        lblBanHang = new javax.swing.JLabel();
        pnKhachHang = new javax.swing.JPanel();
        lblKH = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        pnKhuyenMai = new javax.swing.JPanel();
        lblKM = new javax.swing.JLabel();
        lblKhuyenMai = new javax.swing.JLabel();
        pnSanPham = new javax.swing.JPanel();
        lblSP = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        pnNhanVien = new javax.swing.JPanel();
        lblNV = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        pnThongKe = new javax.swing.JPanel();
        lblTK = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        pnNhapHang = new javax.swing.JPanel();
        lblNH = new javax.swing.JLabel();
        lblNhapHang = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý cửa hàng thời trang");
        setBackground(new java.awt.Color(255, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        welcome.setBackground(new java.awt.Color(255, 153, 0));
        welcome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                welcomeMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 26)); // NOI18N
        jLabel1.setText("Aura 's Fashion");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout welcomeLayout = new javax.swing.GroupLayout(welcome);
        welcome.setLayout(welcomeLayout);
        welcomeLayout.setHorizontalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1))
        );
        welcomeLayout.setVerticalGroup(
            welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBanHang.setBackground(new java.awt.Color(255, 153, 0));
        pnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnBanHangMouseClicked(evt);
            }
        });

        lblBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lblBanHang.png"))); // NOI18N

        lblBanHang.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblBanHang.setText("Bán Hàng");

        javax.swing.GroupLayout pnBanHangLayout = new javax.swing.GroupLayout(pnBanHang);
        pnBanHang.setLayout(pnBanHangLayout);
        pnBanHangLayout.setHorizontalGroup(
            pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBanHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBanHangLayout.setVerticalGroup(
            pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanHangLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBH)
                    .addComponent(lblBanHang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnKhachHang.setBackground(new java.awt.Color(255, 153, 0));
        pnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnKhachHangMouseClicked(evt);
            }
        });

        lblKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lblKhachHang.png"))); // NOI18N

        lblKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblKhachHang.setText("Khách Hàng");

        javax.swing.GroupLayout pnKhachHangLayout = new javax.swing.GroupLayout(pnKhachHang);
        pnKhachHang.setLayout(pnKhachHangLayout);
        pnKhachHangLayout.setHorizontalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnKhachHangLayout.setVerticalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKH)
                    .addComponent(lblKhachHang))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnKhuyenMai.setBackground(new java.awt.Color(255, 153, 0));
        pnKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnKhuyenMaiMouseClicked(evt);
            }
        });

        lblKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lblKhuyenMai.png"))); // NOI18N

        lblKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblKhuyenMai.setText("Khuyến Mãi");

        javax.swing.GroupLayout pnKhuyenMaiLayout = new javax.swing.GroupLayout(pnKhuyenMai);
        pnKhuyenMai.setLayout(pnKhuyenMaiLayout);
        pnKhuyenMaiLayout.setHorizontalGroup(
            pnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKhuyenMai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnKhuyenMaiLayout.setVerticalGroup(
            pnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhuyenMaiLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnKhuyenMaiLayout.createSequentialGroup()
                        .addComponent(lblKhuyenMai)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );

        pnSanPham.setBackground(new java.awt.Color(255, 153, 0));
        pnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnSanPhamMouseClicked(evt);
            }
        });

        lblSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lblsanpham4.png"))); // NOI18N

        lblSanPham.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblSanPham.setText("Sản Phẩm");

        javax.swing.GroupLayout pnSanPhamLayout = new javax.swing.GroupLayout(pnSanPham);
        pnSanPham.setLayout(pnSanPhamLayout);
        pnSanPhamLayout.setHorizontalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSanPhamLayout.setVerticalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSanPham)
                    .addComponent(lblSP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnNhanVien.setBackground(new java.awt.Color(255, 153, 0));
        pnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnNhanVienMouseClicked(evt);
            }
        });

        lblNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lblNhanVien.png"))); // NOI18N

        lblNhanVien.setBackground(new java.awt.Color(255, 153, 0));
        lblNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblNhanVien.setText("Nhân Viên");

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNhanVienLayout.createSequentialGroup()
                .addComponent(lblNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblNhanVien)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnThongKe.setBackground(new java.awt.Color(255, 153, 0));
        pnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnThongKeMouseClicked(evt);
            }
        });

        lblTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lblThongKe.png"))); // NOI18N

        lblThongKe.setBackground(new java.awt.Color(255, 153, 0));
        lblThongKe.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblThongKe.setText("Thống Kê");

        javax.swing.GroupLayout pnThongKeLayout = new javax.swing.GroupLayout(pnThongKe);
        pnThongKe.setLayout(pnThongKeLayout);
        pnThongKeLayout.setHorizontalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongKeLayout.setVerticalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblThongKe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addComponent(lblTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnNhapHang.setBackground(new java.awt.Color(255, 153, 0));
        pnNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnNhapHangMouseClicked(evt);
            }
        });

        lblNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lblNhapHang.png"))); // NOI18N

        lblNhapHang.setBackground(new java.awt.Color(255, 153, 0));
        lblNhapHang.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblNhapHang.setText("Nhập Hàng");

        javax.swing.GroupLayout pnNhapHangLayout = new javax.swing.GroupLayout(pnNhapHang);
        pnNhapHang.setLayout(pnNhapHangLayout);
        pnNhapHangLayout.setHorizontalGroup(
            pnNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNhapHangLayout.setVerticalGroup(
            pnNhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhapHangLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblNhapHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnNhapHangLayout.createSequentialGroup()
                .addComponent(lblNH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addGap(9, 9, 9))
            .addComponent(pnThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(pnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mau-logo-shop-quan-ao-7.jpg"))); // NOI18N
        jLabel14.setText("Chào Mừng Đến Với  AURA's  FASHION");
        pnMain.add(jLabel14, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1126, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 235, Short.MAX_VALUE)
                    .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //        thongKe = new jpanelThongKe();
        welcome.setBackground(new Color(255,153,0));
        pnBanHang.setBackground(new Color(255,153,0));
        pnKhachHang.setBackground(new Color(255,153,0));
        pnKhuyenMai.setBackground(new Color(255,153,0));
        pnSanPham.setBackground(new Color(255,153,0));
        pnNhanVien.setBackground(new Color(255,153,0));
        pnThongKe.setBackground(new Color(255,153,0));
        pnMain.removeAll();
        pnMain.add(jLabel14);
        pnMain.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void welcomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_welcomeMouseClicked
        //        welcome.setBackground(new Color(255,204,204));
        //        pnBanHang.setBackground(new Color(255,204,204));
        //        pnKhuyenMai.setBackground(new Color(255,204,204));
        //        pnSanPham.setBackground(new Color(255,204,204));
        //        pnNhanVien.setBackground(new Color(255,204,204));
        //        pnKhachHang.setBackground(new Color(255,204,204));
        //        pnThongKe.setBackground(new Color(255,204,204));

        //        pnMain.removeAll();
        //        pnMain.add(jLabel14);
        //        pnMain.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_welcomeMouseClicked

    private void pnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBanHangMouseClicked
        pnBanHang.setBackground(Color.LIGHT_GRAY);
        pnKhachHang.setBackground(new Color(255,153,0));
        pnKhuyenMai.setBackground(new Color(255,153,0));
        pnSanPham.setBackground(new Color(255,153,0));
        pnNhanVien.setBackground(new Color(255,153,0));
        pnThongKe.setBackground(new Color(255,153,0));
        pnNhapHang.setBackground(new Color(255,153,0));

        banHang = new jpanelBanHang();
        pnMain.removeAll();
        pnMain.add(banHang);
        pnMain.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_pnBanHangMouseClicked

    private void pnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKhachHangMouseClicked
        pnBanHang.setBackground(new Color(255,153,0));
        pnKhachHang.setBackground(Color.LIGHT_GRAY);
        pnKhuyenMai.setBackground(new Color(255,153,0));
        pnSanPham.setBackground(new Color(255,153,0));
        pnNhanVien.setBackground(new Color(255,153,0));
        pnThongKe.setBackground(new Color(255,153,0));
        pnNhapHang.setBackground(new Color(255,153,0));

        khachHang = new jpanelKhachHang();
        pnMain.removeAll();
        pnMain.add(khachHang);
        pnMain.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_pnKhachHangMouseClicked

    private void pnKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKhuyenMaiMouseClicked
        pnBanHang.setBackground(new Color(255,153,0));
        pnKhachHang.setBackground(new Color(255,153,0));
        pnKhuyenMai.setBackground(Color.LIGHT_GRAY);
        pnSanPham.setBackground(new Color(255,153,0));
        pnNhanVien.setBackground(new Color(255,153,0));
        pnThongKe.setBackground(new Color(255,153,0));
        pnNhapHang.setBackground(new Color(255,153,0));

        khuyenMai = new jpanelKhuyenMai();
        pnMain.removeAll();
        pnMain.add(khuyenMai);
        pnMain.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_pnKhuyenMaiMouseClicked

    private void pnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSanPhamMouseClicked
        pnBanHang.setBackground(new Color(255,153,0));
        pnKhachHang.setBackground(new Color(255,153,0));
        pnKhuyenMai.setBackground(new Color(255,153,0));
        pnSanPham.setBackground(Color.LIGHT_GRAY);
        pnNhanVien.setBackground(new Color(255,153,0));
        pnThongKe.setBackground(new Color(255,153,0));
        pnNhapHang.setBackground(new Color(255,153,0));

        sanPham = new jpanelSanPham();
        pnMain.removeAll();
        pnMain.add(sanPham);
        pnMain.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_pnSanPhamMouseClicked

    private void pnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNhanVienMouseClicked
        pnBanHang.setBackground(new Color(255,153,0));
        pnKhachHang.setBackground(new Color(255,153,0));
        pnKhuyenMai.setBackground(new Color(255,153,0));
        pnSanPham.setBackground(new Color(255,153,0));
        pnNhanVien.setBackground(Color.LIGHT_GRAY);
        pnThongKe.setBackground(new Color(255,153,0));
        pnNhapHang.setBackground(new Color(255,153,0));

        nhanVien = new jpanelNhanVien();
        pnMain.removeAll();
        pnMain.add(nhanVien);
        pnMain.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_pnNhanVienMouseClicked

    private void pnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThongKeMouseClicked
        pnBanHang.setBackground(new Color(255,153,0));
        pnKhachHang.setBackground(new Color(255,153,0));
        pnKhuyenMai.setBackground(new Color(255,153,0));
        pnSanPham.setBackground(new Color(255,153,0));
        pnNhanVien.setBackground(new Color(255,153,0));
        pnThongKe.setBackground(Color.LIGHT_GRAY);
        pnNhapHang.setBackground(new Color(255,153,0));

        thongKe = new jpanelThongKe();
        pnMain.removeAll();
        pnMain.add(thongKe);
        pnMain.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_pnThongKeMouseClicked

    private void pnNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNhapHangMouseClicked
        pnBanHang.setBackground(new Color(255,153,0));
        pnKhachHang.setBackground(new Color(255,153,0));
        pnKhuyenMai.setBackground(new Color(255,153,0));
        pnSanPham.setBackground(new Color(255,153,0));
        pnNhapHang.setBackground(Color.LIGHT_GRAY);
        pnNhanVien.setBackground(new Color(255,153,0));
        pnThongKe.setBackground(new Color(255,153,0));

        nhapHang = new jpanelNhapHang();
        pnMain.removeAll();
        pnMain.add(nhapHang);
        pnMain.validate();
        
        
       
    }//GEN-LAST:event_pnNhapHangMouseClicked
    private void addControls() {
        
        phanquyen quyen = phanquyenBUS.quyenTK;

        if (quyen.getQuanlynhaphang()== 0) {
           jpnnhaphang = new jpanelNhapHang();
           pnNhapHang.setLayout(new BorderLayout());
           pnNhapHang.add(jpnnhaphang);
           lblNhapHang.setVisible(false);
           jpnnhaphang.setVisible(false);
           lblNH.setVisible(false);
        }

        if (quyen.getQuanlybanhang()== 0) {
            jpnbanhang = new jpanelBanHang();
            pnBanHang.setLayout(new BorderLayout());
            pnBanHang.add(jpnbanhang);
            lblBanHang.setVisible(false);
            jpnbanhang.setVisible(false);
            lblBH.setVisible(false);
        }

        if (quyen.getQuanlynhanvien()== 0) {
            jpnnhanvien = new jpanelNhanVien();
            pnNhanVien.setLayout(new BorderLayout());
            pnNhanVien.add(jpnnhanvien);
            lblNhanVien.setVisible(false);
            jpnnhanvien.setVisible(false);
            lblNV.setVisible(false);
        }

        if (quyen.getQuanlykhachhang()== 0) {
            jpnkhachang = new jpanelKhachHang();
            pnKhachHang.setLayout(new BorderLayout());
            pnKhachHang.add(jpnkhachang);
            lblKhachHang.setVisible(false);
            jpnkhachang.setVisible(false);
            lblKH.setVisible(false);
        }

        if (quyen.getQuanlykhuyenmai()== 0) {
            jpnkhuyenmai = new jpanelKhuyenMai();
            pnKhuyenMai.setLayout(new BorderLayout());
            pnKhuyenMai.add(jpnkhuyenmai);
            lblKhuyenMai.setVisible(false);
            jpnkhuyenmai.setVisible(false);
            lblKM.setVisible(false);
        }
         if (quyen.getQuanlythongke()== 0) {
            jpnthongke = new jpanelThongKe();
            pnThongKe.setLayout(new BorderLayout());
            pnThongKe.add(jpnthongke);
            lblThongKe.setVisible(false);
            jpnthongke.setVisible(false);
            lblTK.setVisible(false);
        }
          if (quyen.getQuanlysanpham()== 0) {
            jpnsanpham = new jpanelSanPham();
            pnSanPham.setLayout(new BorderLayout());
            pnSanPham.add(jpnsanpham);
            lblSanPham.setVisible(false);
            jpnsanpham.setVisible(false);
            lblSP.setVisible(false);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienAdmin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienAdmin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBH;
    private javax.swing.JLabel lblBanHang;
    private javax.swing.JLabel lblKH;
    private javax.swing.JLabel lblKM;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblNH;
    private javax.swing.JLabel lblNV;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblNhapHang;
    private javax.swing.JLabel lblSP;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblTK;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JPanel pnBanHang;
    private javax.swing.JPanel pnKhachHang;
    private javax.swing.JPanel pnKhuyenMai;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnNhapHang;
    private javax.swing.JPanel pnSanPham;
    private javax.swing.JPanel pnThongKe;
    private javax.swing.JPanel welcome;
    // End of variables declaration//GEN-END:variables
}
